### ISSUE TITLE
Discriminatory terms present in flavors.txt

### ISSUE THREAD

**Issue by gytdau** [pharmapsychotic/clip-interrogator#10]
A quick CTRL+F revealed at least one term in flavors.txt that uses a slur --

![image](https://user-images.githubusercontent.com/8823299/199613180-be35c6a4-659a-43e5-9bb2-e69cb990104b.png)

I wasn't able to find many more, so not sure if this is a one-off.

**Comment by pharmapsychotic** [comment]
Good find, thank you I'll fix!

**Comment by maplepy** [comment]
What do flavors do exactly ?

**Comment by pharmapsychotic** [comment]
they are chained together to improve the prompt

**Comment by pharmapsychotic** [comment]
Fixed!

**Comment by maplepy** [comment]
Ooh alright thanks! You use them in the prompt itself then right?
