### ISSUE TITLE
Pip intall issue with the example

### ISSUE THREAD

**Issue by nepeee** [pharmapsychotic/clip-interrogator#13]
After installing it from pip and try to run the example i got the following error:
ImportError: cannot import name 'Interrogator' from partially initialized module 'clip_interrogator' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/clip_interrogator/__init__.py)

I use Python 3.8.2

**Comment by nepeee** [comment]
fixed, it was an env error

**Comment by pharmapsychotic** [comment]
ok, cool! i hope to simplify it so the other repo's won't need to be installed that way but didn't get that far yet. thanks for trying the library out!
