### ISSUE TITLE
Is output length hardcoded?

### ISSUE THREAD

**Issue by kabachuha** [pharmapsychotic/clip-interrogator#14]
Hello, @pharmapsychotic!

I enjoy using your tool very much. But it seems that your top item rankings length are hardcoded and cannot be changed in the config nor passes as a function argument when using 'clip-interrogator' from pip.

https://github.com/pharmapsychotic/clip-interrogator/blob/8f5ddce2b3908f770d2b9a404f99d256c10adea2/clip_interrogator/clip_interrogator.py#L178

https://github.com/pharmapsychotic/clip-interrogator/blob/8f5ddce2b3908f770d2b9a404f99d256c10adea2/clip_interrogator/clip_interrogator.py#L135

**Comment by pharmapsychotic** [comment]
I chose these to be large enough so the generated prompts hit the 77 token limit. (minus the last flavor that would partially fit) Have you gotten any that seem too short?

**Comment by pharmapsychotic** [comment]
@kabachuha there's optional `max_flavors` parameter to each of the interrogate methods now. I have speed up coming to the main interrogate method coming soon too...

**Comment by kabachuha** [comment]
Great, thanks!
