### ISSUE TITLE
Trying to use with diffusers/upgrade to recent transformers

### ISSUE THREAD

**Issue by TheOneTrueGuy** [pharmapsychotic/clip-interrogator#17]
I moved the transformers install to version 4.24.0 and after the BLIP/CLIP which got rid of the "module transformers has no attribute FeatureExtractionMixin" problem but now it is doing this:
![errors2](https://user-images.githubusercontent.com/3240071/204154920-5b84e3df-88e0-48ca-9606-365360e75b42.PNG)

The following `model_kwargs` are not used by the model: ['encoder_hidden_states', 'encoder_attention_mask']

I realize this is a problem with Transformers, maybe not CI but I can't 100% tell anymore so I thought it might be something you need to know about. Right now Diffusers and CLIP Interrogator can not run in the same environment.

**Comment by knoopx** [comment]
btw this workarounds the problem meanwhile it gets fixed:

```python
from transformers.generation_utils import GenerationMixin

def _no_validate_model_kwargs(self, model_kwargs):
    pass

GenerationMixin._validate_model_kwargs = _no_validate_model_kwargs
```

**Comment by AmanKishore** [comment]
You can use: https://github.com/MirageML/BLIP in the meantime
`pip3 install -e git+https://github.com/MirageML/BLIP.git@main#egg=blip`

**Comment by TheOneTrueGuy** [comment]
That did it! Thanks Aman!

**Comment by jhrsya** [comment]
> btw this workarounds the problem meanwhile it gets fixed:
> 
> ```python
> from transformers.generation_utils import GenerationMixin
> 
> def _no_validate_model_kwargs(self, model_kwargs):
>     pass
> 
> GenerationMixin._validate_model_kwargs = _no_validate_model_kwargs
> ```

Great! It works for me. Thankyou!
