### ISSUE TITLE
Issue with SD2

### ISSUE THREAD

**Issue by AmanKishore** [pharmapsychotic/clip-interrogator#20]
When running SD2 I' getting the following error:
Command: `ci = Interrogator(Config(clip_model_name="ViT-H-14/laion2b_s32b_b79k"))`

```RuntimeError: Model ViT-H-14/laion2b_s32b_b79k not found; available models = ['RN50', 'RN101', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px']```

**Comment by pharmapsychotic** [comment]
hmm in what way are you running it? looks like that list is coming from the OpenAI clip library but the latest code is now using open_clip instead. with open_clip the list of models comes from `open_clip.list_pretrained()`

**Comment by pharmapsychotic** [comment]
ohh you're using the version available via pip! yes, sorry I did not push the updated version to pip yet so it expects one of those OpenAI models. I'll do that now

**Comment by pharmapsychotic** [comment]
Assuming that was the issue you should now be able to `pip3 install --upgrade clip-interrogator` to get 0.3.0 which supports ViT-H-14/laion2b_s32b_b79k

**Comment by AmanKishore** [comment]
Thank you!
