### ISSUE TITLE
RuntimeError: expected scalar type Float but found Half

### ISSUE THREAD

**Issue by bsdero** [pharmapsychotic/clip-interrogator#25]
I've been getting this error in my M1 lately:

│ /opt/homebrew/lib/python3.10/site-packages/clip_interrogator/clip_interrogator.py:205 in         │
│ interrogate                                                                                      │
│                                                                                                  │
│   202 │   │   │   best_prompt = t.rank(image_features, 1)[0]                                     │
│   203 │   │   │   best_sim = self.similarity(image_features, best_prompt)                        │
│   204 │   │                                                                                      │
│ ❱ 205 │   │   check_multi_batch([best_medium, best_artist, best_trending, best_movement])        │
│   206 │   │                                                                                      │
│   207 │   │   extended_flavors = set(flaves)                                                     │
│   208 │   │   for _ in tqdm(range(max_flavors), desc="Flavor chain", disable=self.config.quiet   │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/clip_interrogator/clip_interrogator.py:202 in         │
│ check_multi_batch                                                                                │
│                                                                                                  │
│   199 │   │   │   │   prompts.append(prompt)                                                     │
│   200 │   │   │                                                                                  │
│   201 │   │   │   t = LabelTable(prompts, None, self.clip_model, self.tokenize, self.config)     │
│ ❱ 202 │   │   │   best_prompt = t.rank(image_features, 1)[0]                                     │
│   203 │   │   │   best_sim = self.similarity(image_features, best_prompt)                        │
│   204 │   │                                                                                      │
│   205 │   │   check_multi_batch([best_medium, best_artist, best_trending, best_movement])        │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/clip_interrogator/clip_interrogator.py:295 in rank    │
│                                                                                                  │
│   292 │                                                                                          │
│   293 │   def rank(self, image_features: torch.Tensor, top_count: int=1) -> List[str]:           │
│   294 │   │   if len(self.labels) <= self.chunk_size:                                            │
│ ❱ 295 │   │   │   tops = self._rank(image_features, self.embeds, top_count=top_count)            │
│   296 │   │   │   return [self.labels[i] for i in tops]                                          │
│   297 │   │                                                                                      │
│   298 │   │   num_chunks = int(math.ceil(len(self.labels)/self.chunk_size))                      │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/clip_interrogator/clip_interrogator.py:289 in _rank   │
│                                                                                                  │
│   286 │   │   top_count = min(top_count, len(text_embeds))                                       │
│   287 │   │   text_embeds = torch.stack([torch.from_numpy(t) for t in text_embeds]).to(self.de   │
│   288 │   │   with torch.cuda.amp.autocast():                                                    │
│ ❱ 289 │   │   │   similarity = image_features @ text_embeds.T                                    │
│   290 │   │   _, top_labels = similarity.float().cpu().topk(top_count, dim=-1)                   │
│   291 │   │   return [top_labels[0][i].numpy() for i in range(top_count)]                        │
│   292

**Comment by pharmapsychotic** [comment]
sorry I thought this was fixed too! i'll check it out!

**Comment by pharmapsychotic** [comment]
okay should be fixed now with version 0.3.2!
