### ISSUE TITLE
Installation error during "Download preprocessed cache files..."

### ISSUE THREAD

**Issue by TheOneTrueGuy** [pharmapsychotic/clip-interrogator#28]
During the CLIP Interrogator install the line that reads
 from clip_interrogator import Config, Interrogator
throws an error in the [numpy/__init__.py] in __getattr__(attr) module 
error:
module 'numpy' has no attribute '_no_nep50_warning'

which ultimately led me to this page: https://numpy.org/neps/nep-0050-scalar-promotion.html

but I don't know how to fix it. Or I would have already.

![bliperror](https://user-images.githubusercontent.com/3240071/208885016-440693ef-add3-4abf-bbbf-2b47a40c1b4f.png)

**Comment by TheOneTrueGuy** [comment]
oops, forgot the code to reproduce error, can be found in notebook form here: https://github.com/TheOneTrueGuy/DigitalDayDream

**Comment by pharmapsychotic** [comment]
Getting this in the main CLIP Interrogator notebook as well. Looks like something changed on the Colab side breaking transformers / tensorflow. 🤔 Investigating!

**Comment by TheOneTrueGuy** [comment]
Opensource/github desperately need a "retrace to last working version" feature. 
Biggest weakness opensource has is one small change up the chain collapsing entire swathes of dependent projects.

**Comment by pharmapsychotic** [comment]
Fixed by removing bunch of pip installs from notebook. The fairscale library was triggering install of incompatible version of numpy.

**Comment by pharmapsychotic** [comment]
You can apply the same removal to Clipxloop as this change
https://github.com/pharmapsychotic/clip-interrogator/commit/180cbc4f7bcd4ca67afc505f76498a39920f9d39
