### ISSUE TITLE
Difference between implementation with Web UI.

### ISSUE THREAD

**Issue by njan-creative** [pharmapsychotic/clip-interrogator#31]
Differences with implementation at 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/interrogate.py

The model loaded in other repository is 
model_url='https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth',
where as clip interrogator uses
blip_model_url: str = 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth'

**Comment by pharmapsychotic** [comment]
Good question! I'll run both models through my benchmark suite and see which comes out with closer alignment to ViTL and ViTH

**Comment by pharmapsychotic** [comment]
So I tested it and the base model is worse for most but better for a few. I can make it a simpler option to use it for anyone who wants to switch between the two.

**Comment by pharmapsychotic** [comment]
if you use the source directly now there is new option on Config object `blip_model_type` which can be set to "base" or "large". i expanded my benchmark image set and ran through both and find large outperforms base so i will keep large as default.

**Comment by pzhren** [comment]
> if you use the source directly now there is new option on Config object `blip_model_type` which can be set to "base" or "large". i expanded my benchmark image set and ran through both and find large outperforms base so i will keep large as default.如果你现在直接使用源代码，在配置对象 `blip_model_type` 上有一个新的选项，可以设置为“base”或“large”。我扩展了我的基准图像集，并通过两者运行，发现大优于基地，所以我将保持大作为默认值。

when i run "ci = Interrogator(Config(blip_model_type=None))", it show：
got an unexpected keyword argument 'blip_model_type'
how should i handle this?
