### ISSUE TITLE
BLIP med_config can't be found

### ISSUE THREAD

**Issue by radames** [pharmapsychotic/clip-interrogator#32]
Hello, when I install your `git+https://github.com/pharmapsychotic/BLIP.git@lib#egg=blip` BLIP fork, without the `-e` option, clip-interrogator can't find the `med_config` file

```
pip install git+https://github.com/pharmapsychotic/BLIP.git@lib#egg=blip
pip install clip-interrogator==0.3.2
```

```
pip install -e git+https://github.com/pharmapsychotic/BLIP.git@lib#egg=blip
pip install clip-interrogator==0.3.2
```

maybe there's is a better way to locate the config file?

https://github.com/pharmapsychotic/clip-interrogator/blob/180cbc4f7bcd4ca67afc505f76498a39920f9d39/clip_interrogator/clip_interrogator.py#L55-L63

**Comment by ZetiMente** [comment]
Oh dang, I just got this issue.

**Comment by pharmapsychotic** [comment]
Update the BLIP dependency so can you give it a try now like this  (updated instructions in README)

```
# install torch with GPU support for example:
pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu117

# install clip-interrogator and blip
pip install clip-interrogator==0.3.3
pip install git+https://github.com/pharmapsychotic/BLIP.git
```

**Comment by ZetiMente** [comment]
@pharmapsychotic I'm still getting the error. Did it work for you @radames ?

I'm getting

```
    with open(json_file, "r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/pypoetry/virtualenvs/mind-9TtSrW0h-py3.10/lib/python3.10/site-packages/configs/med_config.json'
```

I have this in my pyproject.toml

```
clip-interrogator = "^0.3.3"
blip = { git = "https://github.com/pharmapsychotic/BLIP.git"}
```

**Comment by pharmapsychotic** [comment]
@ZetiMente okay should be able to just do `pip install clip-interrogator==0.3.5` now and it'll pull in the blip dependency it needs

**Comment by ZetiMente** [comment]
> @ZetiMente okay should be able to just do `pip install clip-interrogator==0.3.5` now and it'll pull in the blip dependency it needs

Works fine on MacOS but on Linux Debian 11. 

`ModuleNotFoundError: No module named 'pip'` when trying to do `poetry add clip-interrogator` 
& 
`ModuleNotFoundError: No module named 'setuptools.command.build' when trying to do 'pip install clip-interrogator=0.3.5

**Comment by pharmapsychotic** [comment]
hmm I'm not familiar with poetry. sounds like maybe pip instead fully installed on your Debian setup? maybe `sudo apt install python3-pip` can fix?

**Comment by pharmapsychotic** [comment]
Going to close issue out now. Latest 0.5.1 version is using new `blip-ci` package on pypi with fewer dependencies and everything packaged up nicely by now. thanks so much guys!
