### ISSUE TITLE
how do i install clip-interrogator in my local computer?

### ISSUE THREAD

**Issue by xxl2005** [pharmapsychotic/clip-interrogator#36]
Hello, how do I install the clip interrogator on my local computer? i use linux

**Comment by geocine** [comment]
Its on the README https://github.com/pharmapsychotic/clip-interrogator#using-as-a-library

**Comment by xxl2005** [comment]
> Its on the README https://github.com/pharmapsychotic/clip-interrogator#using-as-a-library

yes but i need a detailed description tried to install but it fails

**Comment by geocine** [comment]
You need to show the error so that someone can help you.

**Comment by xxl2005** [comment]
> You need to show the error so that someone can help you.

[tobias@tobias-b550iaorusproax ~]$ pip install clip-interrogator==0.3.5
Defaulting to user installation because normal site-packages is not writeable
Collecting clip-interrogator==0.3.5
  Using cached clip_interrogator-0.3.5-py3-none-any.whl
Requirement already satisfied: torchvision in ./.local/lib/python3.10/site-packages (from clip-interrogator==0.3.5) (0.13.1+cu116)
Requirement already satisfied: Pillow in /usr/lib/python3.10/site-packages (from clip-interrogator==0.3.5) (9.3.0)
Requirement already satisfied: requests in /usr/lib/python3.10/site-packages (from clip-interrogator==0.3.5) (2.28.1)
Collecting open-clip-torch
  Using cached open_clip_torch-2.10.1-py3-none-any.whl (1.5 MB)
Requirement already satisfied: torch in ./.local/lib/python3.10/site-packages (from clip-interrogator==0.3.5) (1.12.1+cu116)
Requirement already satisfied: tqdm in ./.local/lib/python3.10/site-packages (from clip-interrogator==0.3.5) (4.64.1)
Collecting blip-vit
  Using cached blip_vit-0.0.3-py3-none-any.whl
Collecting timm==0.4.12
  Using cached timm-0.4.12-py3-none-any.whl (376 kB)
Collecting fairscale==0.4.4
  Using cached fairscale-0.4.4-py3-none-any.whl
Collecting pycocoevalcap
  Using cached pycocoevalcap-1.2-py3-none-any.whl (104.3 MB)
Collecting transformers==4.15.0
  Using cached transformers-4.15.0-py3-none-any.whl (3.4 MB)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in ./.local/lib/python3.10/site-packages (from transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (0.11.1)
Collecting tokenizers<0.11,>=0.10.1
  Using cached tokenizers-0.10.3.tar.gz (212 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3.10/site-packages (from transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (6.0)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.10/site-packages (from transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (21.3)
Collecting sacremoses
  Using cached sacremoses-0.0.53-py3-none-any.whl
Requirement already satisfied: numpy>=1.17 in /usr/lib/python3.10/site-packages (from transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (1.23.5)
Requirement already satisfied: filelock in /usr/lib/python3.10/site-packages (from transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (3.8.2)
Requirement already satisfied: regex!=2019.12.17 in ./.local/lib/python3.10/site-packages (from transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (2022.10.31)
Requirement already satisfied: typing-extensions in /usr/lib/python3.10/site-packages (from torch->clip-interrogator==0.3.5) (4.4.0)
Requirement already satisfied: protobuf==3.20.* in ./.local/lib/python3.10/site-packages (from open-clip-torch->clip-interrogator==0.3.5) (3.20.3)
Collecting sentencepiece
  Using cached sentencepiece-0.1.97-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Requirement already satisfied: ftfy in ./.local/lib/python3.10/site-packages (from open-clip-torch->clip-interrogator==0.3.5) (6.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests->clip-interrogator==0.3.5) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests->clip-interrogator==0.3.5) (1.26.12)
Requirement already satisfied: wcwidth>=0.2.5 in /usr/lib/python3.10/site-packages (from ftfy->open-clip-torch->clip-interrogator==0.3.5) (0.2.5)
Collecting pycocotools>=2.0.2
  Using cached pycocotools-2.0.6-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.10/site-packages (from packaging>=20.0->transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (3.0.9)
Requirement already satisfied: matplotlib>=2.1.0 in /usr/lib/python3.10/site-packages (from pycocotools>=2.0.2->pycocoevalcap->blip-vit->clip-interrogator==0.3.5) (3.6.2)
Requirement already satisfied: joblib in /usr/lib/python3.10/site-packages (from sacremoses->transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (1.2.0)
Requirement already satisfied: click in /usr/lib/python3.10/site-packages (from sacremoses->transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (8.1.3)
Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from sacremoses->transformers==4.15.0->blip-vit->clip-interrogator==0.3.5) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/lib/python3.10/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap->blip-vit->clip-interrogator==0.3.5) (1.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.10/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap->blip-vit->clip-interrogator==0.3.5) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/lib/python3.10/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap->blip-vit->clip-interrogator==0.3.5) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib/python3.10/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap->blip-vit->clip-interrogator==0.3.5) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3.10/site-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap->blip-vit->clip-interrogator==0.3.5) (2.8.2)
Building wheels for collected packages: tokenizers
  Building wheel for tokenizers (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/tokenizers
      copying py_src/tokenizers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers
      creating build/lib.linux-x86_64-cpython-310/tokenizers/models
      copying py_src/tokenizers/models/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/models
      creating build/lib.linux-x86_64-cpython-310/tokenizers/decoders
      copying py_src/tokenizers/decoders/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/decoders
      creating build/lib.linux-x86_64-cpython-310/tokenizers/normalizers
      copying py_src/tokenizers/normalizers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/normalizers
      creating build/lib.linux-x86_64-cpython-310/tokenizers/pre_tokenizers
      copying py_src/tokenizers/pre_tokenizers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/pre_tokenizers
      creating build/lib.linux-x86_64-cpython-310/tokenizers/processors
      copying py_src/tokenizers/processors/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/processors
      creating build/lib.linux-x86_64-cpython-310/tokenizers/trainers
      copying py_src/tokenizers/trainers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/trainers
      creating build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_unigram.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_bpe.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/char_level_bpe.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/byte_level_bpe.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/bert_wordpiece.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/base_tokenizer.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations
      creating build/lib.linux-x86_64-cpython-310/tokenizers/tools
      copying py_src/tokenizers/tools/visualizer.py -> build/lib.linux-x86_64-cpython-310/tokenizers/tools
      copying py_src/tokenizers/tools/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/tools
      copying py_src/tokenizers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers
      copying py_src/tokenizers/models/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/models
      copying py_src/tokenizers/decoders/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/decoders
      copying py_src/tokenizers/normalizers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/normalizers
      copying py_src/tokenizers/pre_tokenizers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/pre_tokenizers
      copying py_src/tokenizers/processors/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/processors
      copying py_src/tokenizers/trainers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/trainers
      copying py_src/tokenizers/tools/visualizer-styles.css -> build/lib.linux-x86_64-cpython-310/tokenizers/tools
      running build_ext
      running build_rust
      error: can't find Rust compiler
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects

**Comment by geocine** [comment]
@xxl2005 tokenizer is building on your system and it needs the rust compiler. just install it 
> error: can't find Rust compiler
If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs/) is the recommended way to download and update the Rust compiler toolchain.

**Comment by glendaion** [comment]
which command i use? I have this like a script.
from PIL import Image
from clip_interrogator import Config, Interrogator
image = Image.open(image_path).convert('RGB')
ci = Interrogator(Config(clip_model_name="ViT-L-14/openai"))
print(ci.interrogate(image))

**Comment by xxl2005** [comment]
I installed rustup but the error persists?

**Comment by xxl2005** [comment]
thank you very much it worked.

**Comment by pharmapsychotic** [comment]
I switched back to dedicated fork of BLIP for CLIP Interrogator (blip-ci on pypi) and eliminated the `pycocoevalcap` dependency so this shouldn't be issue for people now. Thanks so much @geocine and @xxl2005
