### ISSUE TITLE
Does this work on CPU?

### ISSUE THREAD

**Issue by NightMachinery** [pharmapsychotic/clip-interrogator#4]
Does this work on CPU?

**Comment by dvasya** [comment]
This pull request should work on CPU:
https://github.com/pharmapsychotic/clip-interrogator/pull/9

**Comment by pharmapsychotic** [comment]
It does now yes! Buuuut it is quite slow to do the precomputation. I'm thinking of uploading the precomputed files to huggingface so they can just be downloaded and save that startup time (especially for CPU!)
