### ISSUE TITLE
UnicodeDecodeError on Windows

### ISSUE THREAD

**Issue by yiouyou** [pharmapsychotic/clip-interrogator#41]
When installing it on Ubuntu, these is no problem. But when installing it on Windows, there is 'gbk' UnicodeDecodeError. I guess the issue should be fixed easy by the author. Thanks!!

```
(venv37) PS E:\_Ai\clip_interrogator> pip install clip-interrogator
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting clip-interrogator
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b9/c0/ac7d63330d69bacbe00e057d54db484560020d5acc69f26df8b64f2c3e85/clip-interrogator-0.4.1.tar.gz (786 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "e:\_ai\clip_interrogator\venv37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "e:\_ai\clip_interrogator\venv37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "e:\_ai\clip_interrogator\venv37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\zhuos\AppData\Local\Temp\pip-build-env-dd06cv8m\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\zhuos\AppData\Local\Temp\pip-build-env-dd06cv8m\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\zhuos\AppData\Local\Temp\pip-build-env-dd06cv8m\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 469: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by kazukiave** [comment]
I have same issue.

**Comment by pharmapsychotic** [comment]
hmm never seen this before, I'll try to reproduce on my Windows machine!

**Comment by terracottahaniwa** [comment]
I git clone this repository, and patched up it.
```
diff --git a/setup.py b/setup.py
index fc429f2..7012705 100644
--- a/setup.py
+++ b/setup.py
@@ -11,7 +11,7 @@ setup(
     author_email='me@pharmapsychotic.com',
     url='https://github.com/pharmapsychotic/clip-interrogator',
     description="Generate a prompt from an image",
-    long_description=open('README.md').read(),
+    long_description=open('README.md', encoding='utf-8').read(),
     long_description_content_type="text/markdown",
     packages=find_packages(),
     install_requires=[
```
To building packages, I was using python3.10.x so I had to follow the guide to install Microsoft Visual Studio 2022 and Rust for building.
https://wiki.python.org/moin/WindowsCompilers
https://www.rust-lang.org/ja/tools/install
As written in the python documentation, Install the Python development workload and the optional Python native development tools option. Dependent `tokenizers` was required rust to install.

then, open Visual Studio 2022 Tools Command Prompt from the start menu.
Add the path to rust in the prompt.
`set PATH=%PATH%;%USERPROFILE%\.cargo\bin`
Also, activate venv if necessary.
Finally, in the repository,
`pip install -e .`

**Comment by mudashi33** [comment]
Solve the problem of failing to install the clip-interrogator, prompting 'gbk' codec can't decode byte......
1. (https://files.pythonhosted.org/packages/14/a4/016b479d287b48eb8d35016f0287303f46e90da1c7cff46d8bfb6d7504e8/blip-ci-0.0.2.tar.gz) Download blip - ci file  and unzip it, then edit the setup.py file in the blip-ci-0.0.2 folder, Change the code on line 23 to `long_description=open('README.md', encoding='utf-8').read(),`
2. save the changes, Then compress the blip-ci-0.0.2 folder back to blip-ci-0.0.2.tar.gz to replace the original file
3. Run the `pip install blip-ci-0.0.2.tar.gz` command to install the blip-ci module
4. Run the `pip install clip-interrogator==0.5.4` command to install the clip-interrogator module
5. Successfully run and use CLIP-Interrogator

**Comment by pharmapsychotic** [comment]
Sorry for the trouble, just merged @gantrol 's PR to blip-ci so this should be fixed now
