### ISSUE TITLE
Why are the preprocessed files marked unsafe?

### ISSUE THREAD

**Issue by xzuyn** [pharmapsychotic/clip-interrogator#42]
Only huggingface page i've seen with this, and now they are set to auto-download? Would it be possible to support safetensors instead?

![hfp1](https://user-images.githubusercontent.com/16216325/216804417-3a7eddeb-0ef9-4fcf-bc2c-348555339001.png)
![hfp2](https://user-images.githubusercontent.com/16216325/216804420-18d6c7b9-e2bc-4d0e-93f7-75d80060d3a6.png)

**Comment by pharmapsychotic** [comment]
@xzuyn I investigated safetensors but they just support storing the tensors and not additional metadata so migrating to them is a pain until the format is further along. If you want to skip downloaded the cache files from huggingface you can set `config.download_cache = False` and it will do the precomputation locally.

**Comment by xzuyn** [comment]
That makes sense, maybe in the future then. Can you explain why they might have marked the files as unsafe?

**Comment by pharmapsychotic** [comment]
Yeah it looks like the "unknown dtype" is the issue. Saved to the pickle files is just list of strings, list of tensors for the text embeddings, and a hash of the string list.

**Comment by pharmapsychotic** [comment]
@xzuyn version 0.5.0 of the library has now switched over to safetensors! thanks for filing the issue!
