### ISSUE TITLE
Do the images I insert remain private or public?

### ISSUE THREAD

**Issue by RafaelPalella** [pharmapsychotic/clip-interrogator#45]
If I insert an image to derive text, is the image published somewhere or does it remain private?

**Comment by pharmapsychotic** [comment]
If you're using the library on your own computer then nothing ever leaves your machine. There is also a Colab notebook for it, Replicate space, and HuggingFace space. Using those you are temporarily uploading image to their servers for processing. On the HuggingFace space there is the option to share your result with the community and it gets posted to the Disccussions tab there.
Hope this answers your question!

**Comment by RafaelPalella** [comment]
So if I put the image on this page, does the image remain private ?
Thanks

https://replicate.com/methexis-inc/img2prompt

**Comment by pharmapsychotic** [comment]
as far as I know yeah.. here's replicate's privacy policy: https://replicate.com/privacy
you can just run CLIP Interrogator on your local computer too
