### ISSUE TITLE
[Request] Add openclip models!

### ISSUE THREAD

**Issue by dillfrescott** [pharmapsychotic/clip-interrogator#5]
Please! This would be so cool!

**Comment by 0xdevalias** [comment]
- https://laion.ai/blog/large-openclip/
  - > We trained three large CLIP models with [OpenCLIP](https://github.com/mlfoundations/open_clip): ViT-L/14, ViT-H/14 and ViT-g/14 (ViT-g/14 was trained only for about a third the epochs compared to the rest). The H/14 model achieves 78.0% zero shot top-1 accuracy on ImageNet and 73.4% on zero-shot image retrieval at Recall@5 on MS COCO. As of September 2022, this is the best open source CLIP model.
- https://huggingface.co/laion
  - https://huggingface.co/laion/CLIP-ViT-L-14-laion2B-s32B-b82K
  - https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K
  - https://huggingface.co/laion/CLIP-ViT-g-14-laion2B-s12B-b42K

**Comment by 0xdevalias** [comment]
These are the changes I made to get it to work in a hacky way:

```diff
 def setup():
     install_cmds = [
         ['pip', 'install', 'ftfy', 'regex', 'tqdm', 'transformers==4.21.2', 'timm', 'fairscale', 'requests'],
-        ['pip', 'install', '-e', 'git+https://github.com/openai/CLIP.git@main#egg=clip'],
+        # ['pip', 'install', '-e', 'git+https://github.com/openai/CLIP.git@main#egg=clip'],
+        ['pip', 'install', 'open_clip_torch'],
         ['pip', 'install', '-e', 'git+https://github.com/pharmapsychotic/BLIP.git@main#egg=blip'],
         ['git', 'clone', 'https://github.com/pharmapsychotic/clip-interrogator.git']
     ]
```

```diff
- import clip
+ # import clip
+ import open_clip as clip
```

```diff
print("Loading CLIP model...")
- clip_model_name = 'ViT-L/14' #@param ['ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px', 'RN101', 'RN50', 'RN50x4', 'RN50x16', 'RN50x64'] {type:'string'}
+ # clip_model_name = 'ViT-L/14' #@param ['ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px', 'RN101', 'RN50', 'RN50x4', 'RN50x16', 'RN50x64'] {type:'string'}
- clip_model, clip_preprocess = clip.load(clip_model_name, device="cuda")
+ # clip_model, clip_preprocess = clip.load(clip_model_name, device="cuda")
+ clip_model, _, clip_preprocess = open_clip.create_model_and_transforms('ViT-L-14', pretrained='laion2b_s32b_b82k')
+ # clip_model, _, clip_preprocess = open_clip.create_model_and_transforms('ViT-H-14', pretrained='laion2b_s32b_b79k')
+ # clip_model, _, clip_preprocess = open_clip.create_model_and_transforms('ViT-g-14', pretrained='laion2b_s12b_b42k')
clip_model.cuda().eval()
```

In this last block of code, you can see the 3 different lines (ViT-L-14 is active, the other 2 commented) for using the new OpenClip models.

In my hacky changes I didn't integrate the model selection into the notebook UI, so you need to change the code to make it work.

**Comment by pharmapsychotic** [comment]
Thanks @0xdevalias !! I'm excited to give it a try and see how open_clip compares performance wise and how different the prompts wind up with ViT-H. I also want to try out the CLIP implementation in huggingface transformers library.

**Comment by 0xdevalias** [comment]
Sounds good! Would love to hear back about your results/findings :)

**Comment by rabidgremlin** [comment]
Now that SD 2.0 has been launched it would be create to get support for OpenCLIP-ViT/H in the interrogator!

**Comment by 0xdevalias** [comment]
@rabidgremlin See my changes above in https://github.com/pharmapsychotic/clip-interrogator/issues/5#issuecomment-1292123997, not many required to make it work.

**Comment by ProGamerGov** [comment]
@pharmapsychotic Can you look into this please? Thanks!

**Comment by ProGamerGov** [comment]
There's a test version of new CLIP model here: https://colab.research.google.com/github/pharmapsychotic/clip-interrogator/blob/open-clip/clip_interrogator.ipynb

**Comment by pharmapsychotic** [comment]
Completed! Thank you @0xdevalias for front running this!

**Comment by 0xdevalias** [comment]
Happy to :)
