### ISSUE TITLE
Clip-Interrogator 2 error, RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

### ISSUE THREAD

**Issue by ProGamerGov** [pharmapsychotic/clip-interrogator#7]
I tried using an image and got the following error:

```
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-5-f6c038c2ae8b>](https://localhost:8080/#) in go(btn)
     47         display(thumb)
     48 
---> 49         prompt = interrogate(image)
     50         IPython.display.clear_output()
     51         show_ui()

6 frames

[/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional_tensor.py](https://localhost:8080/#) in normalize(tensor, mean, std, inplace)
    957     if std.ndim == 1:
    958         std = std.view(-1, 1, 1)
--> 959     tensor.sub_(mean).div_(std)
    960     return tensor
    961 

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
```

**Comment by spro** [comment]
I ran into the same problem with PNGs that had alpha channels - you can remove the alpha channel with imagemagick:

```
convert input.png -alpha off output.png
```

**Comment by 0xdevalias** [comment]
This is the section of code that handles stuff, if you provide a URL it uses `.convert('RGB')`, but if you upload the file directly it doesn't:

https://github.com/pharmapsychotic/clip-interrogator/blob/2486589f24165c8e3b303f84e9dbbea318df83e8/clip_interrogator.ipynb?short_path=9a53df4#L313-L324

By changing this line:

```
image = Image.open(io.BytesIO(file_info['content']))\n",
```

to 

```
image = Image.open(io.BytesIO(file_info['content'])).convert('RGB')\n",
```

It should work for you.

(Answer found on [this StackOverflow answer](https://stackoverflow.com/questions/58496858/pytorch-runtimeerror-the-size-of-tensor-a-4-must-match-the-size-of-tensor-b/58497441#58497441))

**Comment by pharmapsychotic** [comment]
Thanks, I'll test and fix now

**Comment by pharmapsychotic** [comment]
Thanks @0xdevalias and @ProGamerGov !! Fix has been applied now 👍
