### ISSUE TITLE
stuck on "Loading CLIP Interrogator 0.5.4..."

### ISSUE THREAD

**Issue by GeorgeNavarre** [pharmapsychotic/clip-interrogator#71]
I have been trying to test this extension version of clip-interrogator but can't get past "Loading CLIP Interrogator 0.5.4..." I thought possibly it was just taking a while so I let it sit for an hour but it continues to say "Loading CLIP Interrogator 0.5.4..." and hasn't output a prompt.

**Comment by waynoedm** [comment]
CLIP seems broken right now.

**Comment by waynoedm** [comment]
Tried this morning on one of my machines, and it re-downloaded everything and appears to work fine now. I'll try on my other system later tonight.

**Comment by waynoedm** [comment]
Actually just tried. Working on both systems now.

**Comment by GeorgeNavarre** [comment]
Same! thanks for the response1
