### ISSUE TITLE
About Independent Use

### ISSUE THREAD

**Issue by Ading163** [pharmapsychotic/clip-interrogator#78]
I want to deploy this feature locally and not embed it in SD. What should I do? Is there a document for reference

**Comment by pharmapsychotic** [comment]
Yes checkout the REAME for instructions on installing and calling from your own scripts:

`pip install clip-interrogator==0.5.4`

```
from PIL import Image
from clip_interrogator import Config, Interrogator
image = Image.open(image_path).convert('RGB')
ci = Interrogator(Config(clip_model_name="ViT-L-14/openai"))
print(ci.interrogate(image))
```

**Comment by pharmapsychotic** [comment]
Or you can clone the repo, install requirements, then run `python run_gradio.py` to run it
