### ISSUE TITLE
in SD 1.5.1 bug(The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0)

### ISSUE THREAD

**Issue by swumagic** [pharmapsychotic/clip-interrogator#89]
Loading CLIP Interrogator 0.5.4...
load checkpoint from M:\SD\sdwebui\models\BLIP\model_base_caption_capfilt_large.pth
Loading CLIP model...
Loaded CLIP model and data in 8.05 seconds.
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0

**Comment by swumagic** [comment]
pip3 install transformers==4.26.1

**Comment by swumagic** [comment]
pip install clip-interrogator==0.6.0
pip install  transformers==4.26.1

**Comment by mokizzz** [comment]
> pip install clip-interrogator==0.6.0

This worked for me!
