### ISSUE TITLE
cannot find python: which version 

### ISSUE THREAD

**Issue by rafstahelin** [pharmapsychotic/clip-interrogator#91]
Have 3.10.6 and 3.10.9 on disk with environment path set to 3.10.9 the 3.106. 

When i run the python -m venv ci_env it says it cannot find python. Is this because i need to use conda? I am on windows. Not sure why this error. thanks

**Comment by pharmapsychotic** [comment]
no you shouldn't need to use conda. try `python3 -m venv ci_env` instead
